---
# tasks file for slave_node
- name: Configuring YUM Repo For K8S Services
  yum_repository:
    name: kubernetes
    description: kubernetes repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
    gpgcheck: 1
    repo_gpgcheck: 1
    enabled: 1
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  register: a
- debug:
        var: a

- name: Installing k8s softwares for master
  package:
    name: "{{ item }}"
    state: present
  loop:
    - kubeadm
    - iproute-tc
    - docker
  register: b
- debug:
        var: b

- name: Enableling  Services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - kubelet
    - docker
  register: c
- debug:
        var: c

- name: Pulling Required K8S Images For Master Node
  command: kubeadm config images pull
  register: d
- debug:
        var: d


- name: Changing CGROUP Driver of Docker
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"]
      }
  register: e
- debug:
        var: e

- name: Restart Docker service
  service:
          name: docker
          state: restarted
  register: f
- debug:
        var: f

- name: Update config file for k8s
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
  register: g
- debug:
        var: g

- name: restarting sysctl
  command: sysctl --system
  register: h
- debug:
        var: h

- name: Running Token File
  shell: "{{ token }}"
  register: i
- debug:
        var: i
